package render

import (
	"strings"
	"testing"

	"github.com/gregberns/adze/internal/config"
	"github.com/gregberns/adze/internal/dag"
	"github.com/gregberns/adze/internal/step"
)

func TestRenderBasicStructure(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "test-step", DependsOn: map[string]string{}, Depth: 0},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name:  "test-step",
			Check: &step.ShellCommand{Args: []string{"sh", "-c", "command -v git"}},
			Apply: &step.ShellCommand{Args: []string{"sh", "-c", "brew install git"}},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Check shebang
	if !strings.HasPrefix(script, "#!/bin/bash\n") {
		t.Error("script should start with #!/bin/bash")
	}

	// Check header comment
	if !strings.Contains(script, "Generated by adze from test.yaml") {
		t.Error("script should contain config path in header")
	}
	if !strings.Contains(script, "Platform: darwin") {
		t.Error("script should contain platform in header")
	}
	if !strings.Contains(script, "Steps: 1") {
		t.Error("script should contain step count in header")
	}

	// Check set -euo pipefail
	if !strings.Contains(script, "set -euo pipefail") {
		t.Error("script should contain set -euo pipefail")
	}

	// Check counter variables
	if !strings.Contains(script, "SUCCEEDED=0") {
		t.Error("script should initialize SUCCEEDED counter")
	}
	if !strings.Contains(script, "SKIPPED=0") {
		t.Error("script should initialize SKIPPED counter")
	}
	if !strings.Contains(script, "FAILED=0") {
		t.Error("script should initialize FAILED counter")
	}

	// Check summary footer
	if !strings.Contains(script, "=== Summary ===") {
		t.Error("script should contain summary footer")
	}
}

func TestRenderAtomicStep(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "homebrew", DependsOn: map[string]string{}, Depth: 0},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name:  "homebrew",
			Check: &step.ShellCommand{Args: []string{"sh", "-c", "command -v brew"}},
			Apply: &step.ShellCommand{Args: []string{"sh", "-c", "install-brew"}},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should have step header
	if !strings.Contains(script, "[1/1] homebrew") {
		t.Error("script should contain step header with numbering")
	}

	// Should have check
	if !strings.Contains(script, "command -v brew") {
		t.Error("script should contain check command")
	}

	// Should have already-satisfied message
	if !strings.Contains(script, "already satisfied") {
		t.Error("script should contain 'already satisfied' message")
	}

	// Should have apply
	if !strings.Contains(script, "install-brew") {
		t.Error("script should contain apply command")
	}

	// Should track success/failure
	if !strings.Contains(script, "SUCCEEDED=$((SUCCEEDED + 1))") {
		t.Error("script should increment SUCCEEDED counter")
	}
	if !strings.Contains(script, "FAILED=$((FAILED + 1))") {
		t.Error("script should increment FAILED counter")
	}
}

func TestRenderBatchStep(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "brew-packages", DependsOn: map[string]string{}, Depth: 0},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name: "brew-packages",
			Items: []step.StepItem{
				{Name: "git"},
				{Name: "curl"},
				{Name: "jq"},
			},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should have batch header
	if !strings.Contains(script, "[1/1] brew-packages (3 items)") {
		t.Error("script should contain batch step header with item count")
	}

	// Should have per-item blocks
	if !strings.Contains(script, "# git") {
		t.Error("script should contain git item comment")
	}
	if !strings.Contains(script, "# curl") {
		t.Error("script should contain curl item comment")
	}
	if !strings.Contains(script, "# jq") {
		t.Error("script should contain jq item comment")
	}

	// Should have per-item check (brew list)
	if !strings.Contains(script, "brew list --formula git") {
		t.Error("script should contain brew check for git")
	}

	// Should have per-item apply (brew install)
	if !strings.Contains(script, "brew install git") {
		t.Error("script should contain brew install for git")
	}

	// Should have batch summary
	if !strings.Contains(script, "brew-packages: $step_ok applied, $step_skip present, $step_fail failed") {
		t.Error("script should contain batch step summary")
	}
}

func TestRenderPreflightSecrets(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets: []config.SecretEntry{
			{Name: "GITHUB_TOKEN", Required: true, Sensitive: true},
			{Name: "OPTIONAL_KEY", Required: false, Sensitive: false},
		},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{},
	}

	script, err := Render(cfg, graph, nil, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should check required env var
	if !strings.Contains(script, "GITHUB_TOKEN") {
		t.Error("script should check required GITHUB_TOKEN")
	}

	// Should mark sensitive with comment
	if !strings.Contains(script, "# (sensitive)") {
		t.Error("script should mark sensitive secrets with comment")
	}

	// Should NOT check optional env var in pre-flight
	if strings.Contains(script, "OPTIONAL_KEY") {
		t.Error("script should not check optional env vars in pre-flight")
	}
}

func TestRenderSensitiveSecretHandling(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets: []config.SecretEntry{
			{Name: "API_KEY", Required: true, Sensitive: true},
		},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{},
	}

	script, err := Render(cfg, graph, nil, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Sensitive secrets should reference as ${VAR_NAME}
	if !strings.Contains(script, "${API_KEY:-}") {
		t.Error("script should reference sensitive secret as ${API_KEY:-}")
	}

	// Should have sensitive comment
	if !strings.Contains(script, "# (sensitive)") {
		t.Error("script should have (sensitive) comment for sensitive secrets")
	}
}

func TestRenderPlatformDispatch(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "go-lang", DependsOn: map[string]string{}, Depth: 0},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name:  "go-lang",
			Check: &step.ShellCommand{Args: []string{"sh", "-c", "command -v go"}},
			PlatformApply: map[string]*step.ShellCommand{
				"darwin": {Args: []string{"sh", "-c", "brew install go"}},
				"ubuntu": {Args: []string{"sh", "-c", "sudo apt-get install -y golang"}},
			},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should use darwin apply
	if !strings.Contains(script, "brew install go") {
		t.Error("script should use darwin platform apply command")
	}

	// Should NOT use ubuntu apply
	if strings.Contains(script, "apt-get") {
		t.Error("script should not contain ubuntu apply command")
	}
}

func TestRenderMultipleStepsOrder(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "first", DependsOn: map[string]string{}, Depth: 0},
			{Name: "second", DependsOn: map[string]string{"first-cap": "first"}, Depth: 1},
			{Name: "third", DependsOn: map[string]string{"second-cap": "second"}, Depth: 2},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name:  "first",
			Check: &step.ShellCommand{Args: []string{"sh", "-c", "check-first"}},
			Apply: &step.ShellCommand{Args: []string{"sh", "-c", "apply-first"}},
		},
		{
			Name:  "second",
			Check: &step.ShellCommand{Args: []string{"sh", "-c", "check-second"}},
			Apply: &step.ShellCommand{Args: []string{"sh", "-c", "apply-second"}},
		},
		{
			Name:  "third",
			Check: &step.ShellCommand{Args: []string{"sh", "-c", "check-third"}},
			Apply: &step.ShellCommand{Args: []string{"sh", "-c", "apply-third"}},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Steps should appear in DAG order
	firstIdx := strings.Index(script, "[1/3] first")
	secondIdx := strings.Index(script, "[2/3] second")
	thirdIdx := strings.Index(script, "[3/3] third")

	if firstIdx == -1 || secondIdx == -1 || thirdIdx == -1 {
		t.Fatalf("expected all step headers in output, got:\n%s", script)
	}

	if firstIdx >= secondIdx || secondIdx >= thirdIdx {
		t.Error("steps should appear in DAG order: first, second, third")
	}
}

func TestRenderNoSteps(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{},
	}

	script, err := Render(cfg, graph, nil, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should still have valid shell script structure
	if !strings.HasPrefix(script, "#!/bin/bash\n") {
		t.Error("empty script should still start with shebang")
	}
	if !strings.Contains(script, "set -euo pipefail") {
		t.Error("empty script should still have set -euo pipefail")
	}
	if !strings.Contains(script, "=== Summary ===") {
		t.Error("empty script should still have summary")
	}
}

func TestShellCommandToString(t *testing.T) {
	tests := []struct {
		name string
		cmd  *step.ShellCommand
		want string
	}{
		{
			name: "nil command",
			cmd:  nil,
			want: "",
		},
		{
			name: "empty args",
			cmd:  &step.ShellCommand{Args: []string{}},
			want: "",
		},
		{
			name: "sh -c pattern",
			cmd:  &step.ShellCommand{Args: []string{"sh", "-c", "echo hello"}},
			want: "echo hello",
		},
		{
			name: "direct command",
			cmd:  &step.ShellCommand{Args: []string{"brew", "install", "git"}},
			want: "brew install git",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := shellCommandToString(tt.cmd)
			if got != tt.want {
				t.Errorf("shellCommandToString() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestExpandHome(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"~/Documents", "$HOME/Documents"},
		{"/usr/local/bin", "/usr/local/bin"},
		{"relative/path", "relative/path"},
		{"~", "~"},                       // only ~/... is expanded
		{"~/", "$HOME/"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := expandHome(tt.input)
			if got != tt.want {
				t.Errorf("expandHome(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestRenderDirectoriesBatch(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "directories", DependsOn: map[string]string{}, Depth: 0},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name: "directories",
			Items: []step.StepItem{
				{Name: "~/projects"},
				{Name: "~/workspace"},
			},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should have mkdir -p with $HOME expansion
	if !strings.Contains(script, "mkdir -p") {
		t.Error("script should contain mkdir -p for directories")
	}
	if !strings.Contains(script, "$HOME/projects") {
		t.Error("script should expand ~/projects to $HOME/projects")
	}
}

func TestRenderBrewCasksBatch(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "brew-casks", DependsOn: map[string]string{}, Depth: 0},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name: "brew-casks",
			Items: []step.StepItem{
				{Name: "visual-studio-code"},
				{Name: "firefox"},
			},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should use --cask flag
	if !strings.Contains(script, "brew install --cask visual-studio-code") {
		t.Error("script should use brew install --cask for casks")
	}

	// Should check with --cask
	if !strings.Contains(script, "brew list --cask visual-studio-code") {
		t.Error("script should check with brew list --cask")
	}
}

func TestRenderPackageWithVersion(t *testing.T) {
	cfg := &config.Config{
		Name:     "test",
		Platform: "darwin",
		Secrets:  []config.SecretEntry{},
	}

	graph := &dag.ResolvedGraph{
		Steps: []dag.ResolvedStep{
			{Name: "brew-packages", DependsOn: map[string]string{}, Depth: 0},
		},
	}

	stepConfigs := []step.StepConfig{
		{
			Name: "brew-packages",
			Items: []step.StepItem{
				{Name: "python", Version: "3.11"},
			},
		},
	}

	script, err := Render(cfg, graph, stepConfigs, "darwin", "test.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(script, "brew install python@3.11") {
		t.Errorf("expected versioned install, got:\n%s", script)
	}
}
