// Package render generates standalone bash scripts from adze configurations.
package render

import (
	"fmt"
	"strings"
	"time"

	"github.com/gregberns/adze/internal/config"
	"github.com/gregberns/adze/internal/dag"
	"github.com/gregberns/adze/internal/step"
)

// Render generates a standalone bash script from a resolved config.
// It emits steps in DAG-topological order.
func Render(cfg *config.Config, graph *dag.ResolvedGraph, stepConfigs []step.StepConfig, platform string, configPath string) (string, error) {
	var sb strings.Builder

	// Index step configs by name for quick lookup
	stepMap := make(map[string]*step.StepConfig, len(stepConfigs))
	for i := range stepConfigs {
		stepMap[stepConfigs[i].Name] = &stepConfigs[i]
	}

	// Collect all secrets with sensitive flag
	sensitiveSecrets := make(map[string]bool)
	for _, s := range cfg.Secrets {
		if s.Sensitive {
			sensitiveSecrets[s.Name] = true
		}
	}

	// Collect required env vars from secrets
	var requiredEnvVars []string
	for _, s := range cfg.Secrets {
		if s.Required {
			requiredEnvVars = append(requiredEnvVars, s.Name)
		}
	}

	totalSteps := len(graph.Steps)
	timestamp := time.Now().UTC().Format(time.RFC3339)

	// 1. Shebang
	sb.WriteString("#!/bin/bash\n")

	// 2. Header comment
	sb.WriteString(fmt.Sprintf("# Generated by adze from %s\n", configPath))
	sb.WriteString(fmt.Sprintf("# Platform: %s\n", platform))
	sb.WriteString(fmt.Sprintf("# Timestamp: %s\n", timestamp))
	sb.WriteString(fmt.Sprintf("# Steps: %d\n", totalSteps))
	sb.WriteString("\n")

	// 3. set -euo pipefail
	sb.WriteString("set -euo pipefail\n")
	sb.WriteString("\n")

	// 4. Counter variables
	sb.WriteString("SUCCEEDED=0\n")
	sb.WriteString("SKIPPED=0\n")
	sb.WriteString("FAILED=0\n")
	sb.WriteString("\n")

	// 5. Pre-flight: check required env vars
	if len(requiredEnvVars) > 0 {
		sb.WriteString("# Pre-flight: check required environment variables\n")
		for _, envVar := range requiredEnvVars {
			comment := ""
			if sensitiveSecrets[envVar] {
				comment = " # (sensitive)"
			}
			sb.WriteString(fmt.Sprintf("if [ -z \"${%s:-}\" ]; then echo \"Error: required env var %s is not set\" >&2; exit 1; fi%s\n",
				envVar, envVar, comment))
		}
		sb.WriteString("\n")
	}

	// 6. Per-step blocks in DAG order
	for i, rs := range graph.Steps {
		sc, ok := stepMap[rs.Name]
		if !ok {
			continue
		}

		stepNum := i + 1

		if len(sc.Items) > 0 {
			// Batch step
			renderBatchStep(&sb, sc, stepNum, totalSteps, sensitiveSecrets, platform)
		} else {
			// Atomic step
			renderAtomicStep(&sb, sc, stepNum, totalSteps, sensitiveSecrets, platform)
		}
		sb.WriteString("\n")
	}

	// 7. Summary footer
	sb.WriteString("# Summary\n")
	sb.WriteString("echo \"\"\n")
	sb.WriteString("echo \"=== Summary ===\"\n")
	sb.WriteString("echo \"  Succeeded: $SUCCEEDED\"\n")
	sb.WriteString("echo \"  Skipped:   $SKIPPED\"\n")
	sb.WriteString("echo \"  Failed:    $FAILED\"\n")
	sb.WriteString("if [ \"$FAILED\" -gt 0 ]; then\n")
	sb.WriteString("  exit 1\n")
	sb.WriteString("fi\n")

	return sb.String(), nil
}

// renderAtomicStep writes a single atomic step block.
func renderAtomicStep(sb *strings.Builder, sc *step.StepConfig, num, total int, sensitive map[string]bool, platform string) {
	checkCmd := resolveCheckCommand(sc)
	applyCmd := resolveApplyCommand(sc, platform)

	sb.WriteString(fmt.Sprintf("echo \"[%d/%d] %s\"\n", num, total, sc.Name))

	if checkCmd != "" {
		sb.WriteString(fmt.Sprintf("if %s &>/dev/null; then\n", escapeForShell(checkCmd)))
		sb.WriteString("  echo \"  \\xe2\\x9c\\x93 already satisfied\"\n")
		sb.WriteString("  SKIPPED=$((SKIPPED + 1))\n")
		sb.WriteString("else\n")
		writeApplyBlock(sb, applyCmd, sc, sensitive, "  ")
		sb.WriteString("fi\n")
	} else if applyCmd != "" {
		// No check command, always apply
		writeApplyBlock(sb, applyCmd, sc, sensitive, "")
	} else {
		sb.WriteString("  echo \"  (no check or apply command)\"\n")
		sb.WriteString("  SKIPPED=$((SKIPPED + 1))\n")
	}
}

// writeApplyBlock writes the apply portion of an atomic step.
func writeApplyBlock(sb *strings.Builder, applyCmd string, sc *step.StepConfig, sensitive map[string]bool, indent string) {
	envPrefix := renderEnvPrefix(sc.Env, sensitive)
	sb.WriteString(fmt.Sprintf("%s%s%s\n", indent, envPrefix, escapeForShell(applyCmd)))
	sb.WriteString(fmt.Sprintf("%sif [ $? -eq 0 ]; then\n", indent))
	sb.WriteString(fmt.Sprintf("%s  echo \"  \\xe2\\x9c\\x93 applied\"\n", indent))
	sb.WriteString(fmt.Sprintf("%s  SUCCEEDED=$((SUCCEEDED + 1))\n", indent))
	sb.WriteString(fmt.Sprintf("%selse\n", indent))
	sb.WriteString(fmt.Sprintf("%s  echo \"  \\xe2\\x9c\\x97 FAILED\" >&2\n", indent))
	sb.WriteString(fmt.Sprintf("%s  FAILED=$((FAILED + 1))\n", indent))
	sb.WriteString(fmt.Sprintf("%sfi\n", indent))
}

// renderBatchStep writes a batch step block with per-item processing.
func renderBatchStep(sb *strings.Builder, sc *step.StepConfig, num, total int, sensitive map[string]bool, platform string) {
	sb.WriteString(fmt.Sprintf("echo \"[%d/%d] %s (%d items)\"\n", num, total, sc.Name, len(sc.Items)))
	sb.WriteString("step_ok=0; step_fail=0; step_skip=0\n")

	for _, item := range sc.Items {
		itemCheckCmd := resolveItemCheckCommand(sc, item, platform)
		itemApplyCmd := resolveItemApplyCommand(sc, item, platform)

		sb.WriteString(fmt.Sprintf("# %s\n", item.Name))

		if itemCheckCmd != "" {
			sb.WriteString(fmt.Sprintf("if %s &>/dev/null; then step_skip=$((step_skip + 1))\n", escapeForShell(itemCheckCmd)))
			sb.WriteString("else\n")
			envPrefix := renderEnvPrefix(sc.Env, sensitive)
			sb.WriteString(fmt.Sprintf("  %s%s\n", envPrefix, escapeForShell(itemApplyCmd)))
			sb.WriteString(fmt.Sprintf("  if [ $? -eq 0 ]; then step_ok=$((step_ok + 1)); else echo \"  \\xe2\\x9c\\x97 %s failed\" >&2; step_fail=$((step_fail + 1)); fi\n", item.Name))
			sb.WriteString("fi\n")
		} else if itemApplyCmd != "" {
			envPrefix := renderEnvPrefix(sc.Env, sensitive)
			sb.WriteString(fmt.Sprintf("%s%s\n", envPrefix, escapeForShell(itemApplyCmd)))
			sb.WriteString(fmt.Sprintf("if [ $? -eq 0 ]; then step_ok=$((step_ok + 1)); else echo \"  \\xe2\\x9c\\x97 %s failed\" >&2; step_fail=$((step_fail + 1)); fi\n", item.Name))
		}
	}

	sb.WriteString(fmt.Sprintf("echo \"  %s: $step_ok applied, $step_skip present, $step_fail failed\"\n", sc.Name))
	sb.WriteString("SUCCEEDED=$((SUCCEEDED + step_ok))\n")
	sb.WriteString("SKIPPED=$((SKIPPED + step_skip))\n")
	sb.WriteString("FAILED=$((FAILED + step_fail))\n")
}

// resolveCheckCommand extracts the check command string from a StepConfig.
func resolveCheckCommand(sc *step.StepConfig) string {
	if sc.Check == nil {
		return ""
	}
	return shellCommandToString(sc.Check)
}

// resolveApplyCommand extracts the apply command, with platform dispatch.
func resolveApplyCommand(sc *step.StepConfig, platform string) string {
	if sc.PlatformApply != nil {
		if cmd, ok := sc.PlatformApply[platform]; ok {
			return shellCommandToString(cmd)
		}
		if cmd, ok := sc.PlatformApply["any"]; ok {
			return shellCommandToString(cmd)
		}
	}
	if sc.Apply == nil {
		return ""
	}
	return shellCommandToString(sc.Apply)
}

// resolveItemCheckCommand generates a check command for a batch item.
func resolveItemCheckCommand(sc *step.StepConfig, item step.StepItem, platform string) string {
	switch sc.Name {
	case "brew-packages":
		return fmt.Sprintf("brew list --formula %s", item.Name)
	case "brew-casks":
		return fmt.Sprintf("brew list --cask %s", item.Name)
	case "apt-packages":
		return fmt.Sprintf("dpkg-query -W %s", item.Name)
	case "directories":
		return fmt.Sprintf("[ -d %q ]", expandHome(item.Name))
	case "zsh-plugins":
		return fmt.Sprintf("[ -d \"$HOME/.oh-my-zsh/custom/plugins/%s\" ]", item.Name)
	case "macos-defaults":
		// item.Name is "domain key", item.Version is type+value
		parts := strings.SplitN(item.Name, " ", 2)
		if len(parts) == 2 {
			return fmt.Sprintf("defaults read %s %s", parts[0], parts[1])
		}
	case "dock-layout":
		return "" // no per-item check
	case "gsettings":
		parts := strings.SplitN(item.Name, " ", 2)
		if len(parts) == 2 {
			return fmt.Sprintf("gsettings get %s %s", parts[0], parts[1])
		}
	}
	return ""
}

// resolveItemApplyCommand generates an apply command for a batch item.
func resolveItemApplyCommand(sc *step.StepConfig, item step.StepItem, platform string) string {
	switch sc.Name {
	case "brew-packages":
		if item.Version != "" {
			return fmt.Sprintf("brew install %s@%s", item.Name, item.Version)
		}
		return fmt.Sprintf("brew install %s", item.Name)
	case "brew-casks":
		return fmt.Sprintf("brew install --cask %s", item.Name)
	case "apt-packages":
		if item.Version != "" {
			return fmt.Sprintf("sudo apt-get install -y %s=%s", item.Name, item.Version)
		}
		return fmt.Sprintf("sudo apt-get install -y %s", item.Name)
	case "directories":
		return fmt.Sprintf("mkdir -p %q", expandHome(item.Name))
	case "zsh-plugins":
		return fmt.Sprintf("git clone https://github.com/zsh-users/%s \"$HOME/.oh-my-zsh/custom/plugins/%s\"", item.Name, item.Name)
	case "macos-defaults":
		parts := strings.SplitN(item.Name, " ", 2)
		if len(parts) == 2 {
			return fmt.Sprintf("defaults write %s %s %s", parts[0], parts[1], item.Version)
		}
	case "dock-layout":
		return fmt.Sprintf("dockutil --add %q --no-restart", item.Name)
	case "gsettings":
		parts := strings.SplitN(item.Name, " ", 2)
		if len(parts) == 2 {
			return fmt.Sprintf("gsettings set %s %s %s", parts[0], parts[1], item.Version)
		}
	}
	return ""
}

// shellCommandToString converts a ShellCommand to its string representation.
// For "sh -c <cmd>" commands, it extracts the inner command.
func shellCommandToString(cmd *step.ShellCommand) string {
	if cmd == nil || len(cmd.Args) == 0 {
		return ""
	}
	// If it's a "sh -c <cmd>" pattern, return the inner command
	if len(cmd.Args) == 3 && cmd.Args[0] == "sh" && cmd.Args[1] == "-c" {
		return cmd.Args[2]
	}
	return strings.Join(cmd.Args, " ")
}

// renderEnvPrefix generates environment variable export prefix for step commands.
func renderEnvPrefix(env []string, sensitive map[string]bool) string {
	if len(env) == 0 {
		return ""
	}
	var parts []string
	for _, e := range env {
		comment := ""
		if sensitive[e] {
			comment = " # (sensitive)"
		}
		parts = append(parts, fmt.Sprintf("%s=${%s}%s", e, e, comment))
	}
	// This is tricky with comments; for simplicity, put env exports on their own lines
	// Actually, for inline use, just reference the vars
	return ""
}

// escapeForShell returns the command as-is (already shell-safe from step configs).
func escapeForShell(cmd string) string {
	return cmd
}

// expandHome replaces ~ with $HOME for shell scripts.
func expandHome(path string) string {
	if strings.HasPrefix(path, "~/") {
		return "$HOME" + path[1:]
	}
	return path
}
